export enum PERMISSIONS {
    USER_CREATE = 'USER:CREATE',
    USER_READ = 'USER:READ',
    USER_UPDATE = 'USER:UPDATE',
    USER_DELETE = 'USER:DELETE',

    USER_PROFILE_UPDATE = 'USER_PROFILE:UPDATE',

    ROOT_ADMIN = 'ROOT:ADMIN',
}
